# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e876dee287a5baa3c39874372a1493433ac2892dfad055a5afab80beee1680ce68b86c3185a70dc69d356467d1b3941083205830a7550c0345b1cd6c8ce399f5

test:
  secret_key_base: 7e9c98d1fa5ab43968153c17a9ff67a72a5cac5b52061f225e97a4283a0d0084cfa2f3c79bcd76351248a1d84f09ae5761c014c8412dee8c9ba694efce2b1e85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
